version: '3.8'

services:

  db:
    image: postgres:16.1
    container_name: booking_db
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

  cache-db:
    image: redis:6.2-alpine
    container_name: booking_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass secret

  booking-ms:
    image: booking-hotel:latest
    container_name: booking-hotel
    restart: always
    environment:
      - JDBC_URL=jdbc:postgresql://booking_db:5432/booking
      - REDIS_URL=redis://booking_cache:6379
    ports:
      - "8080:8080"
    depends_on:
        - db